//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.10 at 10:56:43 AM CET 
//


package com.github.sandor_balazs.sentiment_analysis.jaxb.corpus;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.sandor_balazs.sentiment_analysis.jaxb.corpus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.sandor_balazs.sentiment_analysis.jaxb.corpus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReviewCorpus }
     * 
     */
    public ReviewCorpus createReviewCorpus() {
        return new ReviewCorpus();
    }

    /**
     * Create an instance of {@link OpinionContainer }
     * 
     */
    public OpinionContainer createOpinionContainer() {
        return new OpinionContainer();
    }

    /**
     * Create an instance of {@link Opinion }
     * 
     */
    public Opinion createOpinion() {
        return new Opinion();
    }

    /**
     * Create an instance of {@link SentenceContainer }
     * 
     */
    public SentenceContainer createSentenceContainer() {
        return new SentenceContainer();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link Sentence }
     * 
     */
    public Sentence createSentence() {
        return new Sentence();
    }

}
