//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.10 at 10:56:43 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://github.com/sandor-balazs/sentiment-analysis/jaxb/corpus", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.sandor_balazs.sentiment_analysis.jaxb.corpus;
