//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.10 at 10:56:43 AM CET 
//


package com.github.sandor_balazs.sentiment_analysis.jaxb.corpus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Review complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Review">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sentences" type="{http://github.com/sandor-balazs/sentiment-analysis/jaxb/corpus}SentenceContainer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Review", propOrder = {
    "sentenceContainer"
})
public class Review {

    @XmlElement(name = "sentences", required = true)
    protected SentenceContainer sentenceContainer;
    @XmlAttribute(name = "rid", required = true)
    protected String id;

    /**
     * Gets the value of the sentenceContainer property.
     * 
     * @return
     *     possible object is
     *     {@link SentenceContainer }
     *     
     */
    public SentenceContainer getSentenceContainer() {
        return sentenceContainer;
    }

    /**
     * Sets the value of the sentenceContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SentenceContainer }
     *     
     */
    public void setSentenceContainer(SentenceContainer value) {
        this.sentenceContainer = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
